# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.provider "virtualbox" do |v|
    v.name = "test"
    v.memory = 1024
    v.cpus = 2
  end
  config.vm.hostname = "test"
  config.vm.network "public_network", ip: "192.168.1.40"
  config.vm.define "test"
  config.vm.provision "shell" do |s|
    s.path = "provision.sh"
  end
end
